/* eslint-disable @typescript-eslint/no-non-null-assertion */
/**
 * Pure TypeScript gzip helpers used whenever the browser does not expose the
 * Compression Streams API (e.g. non-secure origins, older Safari builds).
 *
 * The implementation covers the subset of the format we rely on: DEFLATE
 * streams wrapped in a gzip container. Length/distance codes follow the RFC
 * 1951 canonical Huffman rules, matching the output generated by the native
 * CompressionStream pipeline. While the encoder emits “stored” (uncompressed)
 * DEFLATE blocks for simplicity, the decoder fully understands all block
 * types so links generated on modern browsers still open correctly when
 * viewed from restricted environments.
 */

const enum Gzip {
  ID1 = 0x1f,
  ID2 = 0x8b,
  CM_DEFLATE = 8,
  FLG_FTEXT = 1 << 0,
  FLG_FHCRC = 1 << 1,
  FLG_FEXTRA = 1 << 2,
  FLG_FNAME = 1 << 3,
  FLG_FCOMMENT = 1 << 4,
}

const CODE_LENGTH_ORDER = new Uint8Array([
  16, 17, 18, 0, 8, 7, 9, 6, 10, 5, 11, 4, 12, 3, 13, 2, 14, 1, 15,
]);

const LENGTH_BASE = new Uint16Array([
  3, 4, 5, 6, 7, 8, 9, 10,
  11, 13, 15, 17, 19, 23, 27, 31,
  35, 43, 51, 59, 67, 83, 99, 115,
  131, 163, 195, 227, 258,
]);

const LENGTH_EXTRA = new Uint8Array([
  0, 0, 0, 0, 0, 0, 0, 0,
  1, 1, 1, 1, 2, 2, 2, 2,
  3, 3, 3, 3, 4, 4, 4, 4,
  5, 5, 5, 5, 0,
]);

const DIST_BASE = new Uint16Array([
  1, 2, 3, 4, 5, 7, 9, 13,
  17, 25, 33, 49, 65, 97, 129, 193,
  257, 385, 513, 769, 1025, 1537, 2049, 3073,
  4097, 6145, 8193, 12289, 16385, 24577,
]);

const DIST_EXTRA = new Uint8Array([
  0, 0, 0, 0, 1, 1, 2, 2,
  3, 3, 4, 4, 5, 5, 6, 6,
  7, 7, 8, 8, 9, 9, 10, 10,
  11, 11, 12, 12, 13, 13,
]);

type HuffmanTable = {
  table: Uint32Array;
  maxBits: number;
};

function reverseBits(value: number, length: number): number {
  let reversed = 0;
  for (let i = 0; i < length; i += 1) {
    reversed = (reversed << 1) | (value & 1);
    value >>>= 1;
  }
  return reversed;
}

function buildHuffmanTable(codeLengths: Uint8Array): HuffmanTable {
  let maxBits = 0;
  for (let i = 0; i < codeLengths.length; i += 1) {
    maxBits = Math.max(maxBits, codeLengths[i]!);
  }

  if (maxBits === 0) {
    // A table with a single empty code is invalid in DEFLATE streams.
    throw new Error("Invalid Huffman code lengths");
  }

  const tableSize = 1 << maxBits;
  const table = new Uint32Array(tableSize);
  const codeCount = new Uint16Array(maxBits + 1);

  for (let i = 0; i < codeLengths.length; i += 1) {
    codeCount[codeLengths[i]!] += 1;
  }

  const nextCode = new Uint32Array(maxBits + 1);
  let code = 0;
  for (let bits = 1; bits <= maxBits; bits += 1) {
    code = (code + codeCount[bits - 1]!) << 1;
    nextCode[bits] = code;
  }

  for (let symbol = 0; symbol < codeLengths.length; symbol += 1) {
    const length = codeLengths[symbol]!;
    if (length === 0) continue;
    const assignedCode = nextCode[length]!;
    nextCode[length] = assignedCode + 1;
    const reversed = reverseBits(assignedCode, length);
    const fill = 1 << (maxBits - length);
    const entry = (length << 16) | symbol;
    for (let i = 0; i < fill; i += 1) {
      table[reversed | (i << length)] = entry;
    }
  }

  return { table, maxBits };
}

const FIXED_LITERAL_LENGTHS = (() => {
  const lengths = new Uint8Array(288);
  lengths.fill(8, 0, 144);
  lengths.fill(9, 144, 256);
  lengths.fill(7, 256, 280);
  lengths.fill(8, 280, 288);
  return lengths;
})();

const FIXED_DISTANCE_LENGTHS = new Uint8Array(32).fill(5);

const FIXED_LITERAL_TABLE = buildHuffmanTable(FIXED_LITERAL_LENGTHS);
const FIXED_DISTANCE_TABLE = buildHuffmanTable(FIXED_DISTANCE_LENGTHS);

function createCrc32Table(): Uint32Array {
  const table = new Uint32Array(256);
  for (let i = 0; i < 256; i += 1) {
    let value = i;
    for (let bit = 0; bit < 8; bit += 1) {
      value = value & 1 ? (value >>> 1) ^ 0xedb88320 : value >>> 1;
    }
    table[i] = value >>> 0;
  }
  return table;
}

const CRC32_TABLE = createCrc32Table();

function crc32(bytes: Uint8Array): number {
  let crc = 0xffffffff;
  for (let i = 0; i < bytes.length; i += 1) {
    const byte = bytes[i]!;
    const index = (crc ^ byte) & 0xff;
    crc = (crc >>> 8) ^ CRC32_TABLE[index]!;
  }
  return (~crc) >>> 0;
}

function readUint16LE(view: DataView, offset: number): number {
  return view.getUint16(offset, true);
}

function readUint32LE(view: DataView, offset: number): number {
  return view.getUint32(offset, true);
}

function inflateRaw(
  input: Uint8Array,
  output: Uint8Array,
): Uint8Array {
  let inputOffset = 0;
  let bitBuffer = 0;
  let bitLength = 0;
  let outOffset = 0;

  const ensureBits = (bits: number): void => {
    while (bitLength < bits) {
      if (inputOffset >= input.length) {
        throw new Error("Unexpected end of deflate stream");
      }
      bitBuffer |= input[inputOffset++]! << bitLength;
      bitLength += 8;
    }
  };

  const readBits = (bits: number): number => {
    if (bits === 0) return 0;
    ensureBits(bits);
    const value = bitBuffer & ((1 << bits) - 1);
    bitBuffer >>>= bits;
    bitLength -= bits;
    return value;
  };

  const alignByteBoundary = (): void => {
    bitBuffer = 0;
    bitLength = 0;
  };

  const decodeSymbol = (table: HuffmanTable): number => {
    ensureBits(table.maxBits);
    const entry = table.table[bitBuffer & ((1 << table.maxBits) - 1)];
    const bits = entry >>> 16;
    if (bits === 0) {
      throw new Error("Encountered invalid Huffman code");
    }
    bitBuffer >>>= bits;
    bitLength -= bits;
    return entry & 0xffff;
  };

  while (true) {
    const isFinal = readBits(1) === 1;
    const blockType = readBits(2);

    if (blockType === 0) {
      alignByteBoundary();
      if (inputOffset + 4 > input.length) {
        throw new Error("Truncated stored block");
      }
      const len = input[inputOffset]! | (input[inputOffset + 1]! << 8);
      const nlen = input[inputOffset + 2]! | (input[inputOffset + 3]! << 8);
      inputOffset += 4;
      if ((len ^ 0xffff) !== nlen) {
        throw new Error("Stored block length checksum mismatch");
      }
      if (inputOffset + len > input.length) {
        throw new Error("Stored block exceeds input length");
      }
      output.set(input.subarray(inputOffset, inputOffset + len), outOffset);
      inputOffset += len;
      outOffset += len;
    } else if (blockType === 1 || blockType === 2) {
      let literalTable: HuffmanTable;
      let distanceTable: HuffmanTable;

      if (blockType === 1) {
        literalTable = FIXED_LITERAL_TABLE;
        distanceTable = FIXED_DISTANCE_TABLE;
      } else {
        const literalTableResult = buildDynamicTables();
        literalTable = literalTableResult.literal;
        distanceTable = literalTableResult.distance;
      }

      while (true) {
        const symbol = decodeSymbol(literalTable);
        if (symbol < 256) {
          output[outOffset++] = symbol;
        } else if (symbol === 256) {
          break;
        } else {
          const lengthIndex = symbol - 257;
          if (lengthIndex < 0 || lengthIndex >= LENGTH_BASE.length) {
            throw new Error("Invalid length code in deflate stream");
          }
          const baseLength = LENGTH_BASE[lengthIndex]!;
          const extraBits = LENGTH_EXTRA[lengthIndex]!;
          const length = baseLength + readBits(extraBits);

          const distanceSymbol = decodeSymbol(distanceTable);
          if (distanceSymbol >= DIST_BASE.length) {
            throw new Error("Invalid distance code in deflate stream");
          }
          const baseDistance = DIST_BASE[distanceSymbol]!;
          const distanceExtra = DIST_EXTRA[distanceSymbol]!;
          const distance = baseDistance + readBits(distanceExtra);

          if (distance > outOffset) {
            throw new Error("Invalid backward distance in deflate stream");
          }

          for (let i = 0; i < length; i += 1) {
            output[outOffset] = output[outOffset - distance];
            outOffset += 1;
          }
        }
      }
    } else {
      throw new Error("Unsupported deflate block type");
    }

    if (isFinal) {
      break;
    }
  }

  return output.subarray(0, outOffset);

  function buildDynamicTables(): { literal: HuffmanTable; distance: HuffmanTable } {
    const literalCount = readBits(5) + 257;
    const distanceCount = readBits(5) + 1;
    const codeLengthCount = readBits(4) + 4;

    const codeLengthLengths = new Uint8Array(19);
    for (let i = 0; i < codeLengthCount; i += 1) {
      codeLengthLengths[CODE_LENGTH_ORDER[i]!] = readBits(3);
    }

    const codeLengthTable = buildHuffmanTable(codeLengthLengths);
    const literalLengths = new Uint8Array(literalCount);
    const distanceLengths = new Uint8Array(distanceCount);

    const totalCodes = literalCount + distanceCount;
    for (let i = 0; i < totalCodes; ) {
      const symbol = decodeSymbol(codeLengthTable);
      if (symbol <= 15) {
        if (i < literalCount) {
          literalLengths[i] = symbol;
        } else {
          distanceLengths[i - literalCount] = symbol;
        }
        i += 1;
      } else if (symbol === 16) {
        const repeat = 3 + readBits(2);
        const last = i === 0
          ? 0
          : i <= literalCount
            ? literalLengths[i - 1]!
            : distanceLengths[i - literalCount - 1]!;
        for (let r = 0; r < repeat; r += 1) {
          if (i < literalCount) {
            literalLengths[i] = last;
          } else {
            distanceLengths[i - literalCount] = last;
          }
          i += 1;
        }
      } else if (symbol === 17) {
        const repeat = 3 + readBits(3);
        for (let r = 0; r < repeat; r += 1) {
          if (i < literalCount) {
            literalLengths[i] = 0;
          } else {
            distanceLengths[i - literalCount] = 0;
          }
          i += 1;
        }
      } else if (symbol === 18) {
        const repeat = 11 + readBits(7);
        for (let r = 0; r < repeat; r += 1) {
          if (i < literalCount) {
            literalLengths[i] = 0;
          } else {
            distanceLengths[i - literalCount] = 0;
          }
          i += 1;
        }
      } else {
        throw new Error("Invalid code length symbol");
      }
    }

    if (!literalLengths.some((length) => length > 0)) {
      throw new Error("Literal/length table missing codes");
    }
    if (!distanceLengths.some((length) => length > 0)) {
      throw new Error("Distance table missing codes");
    }

    return {
      literal: buildHuffmanTable(literalLengths),
      distance: buildHuffmanTable(distanceLengths),
    };
  }
}

function parseGzipHeader(bytes: Uint8Array): number {
  if (bytes.length < 18) {
    throw new Error("Incomplete gzip payload");
  }

  if (bytes[0] !== Gzip.ID1 || bytes[1] !== Gzip.ID2) {
    throw new Error("Invalid gzip header");
  }

  if (bytes[2] !== Gzip.CM_DEFLATE) {
    throw new Error("Unsupported compression method in gzip stream");
  }

  const flags = bytes[3] ?? 0;
  let offset = 10; // Skip basic header

  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);

  if (flags & Gzip.FLG_FEXTRA) {
    const length = readUint16LE(view, offset);
    offset += 2 + length;
  }

  if (flags & Gzip.FLG_FNAME) {
    while (offset < bytes.length && bytes[offset] !== 0) {
      offset += 1;
    }
    offset += 1;
  }

  if (flags & Gzip.FLG_FCOMMENT) {
    while (offset < bytes.length && bytes[offset] !== 0) {
      offset += 1;
    }
    offset += 1;
  }

  if (flags & Gzip.FLG_FHCRC) {
    offset += 2;
  }

  if (offset >= bytes.length) {
    throw new Error("Truncated gzip header");
  }

  return offset;
}

export function gzipDecompressFallback(bytes: Uint8Array): Uint8Array {
  const dataView = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  const trailerOffset = bytes.length - 8;
  if (trailerOffset <= 0) {
    throw new Error("Gzip payload missing trailer");
  }

  const payloadOffset = parseGzipHeader(bytes);
  const compressedData = bytes.subarray(payloadOffset, trailerOffset);
  const expectedCrc = readUint32LE(dataView, trailerOffset);
  const expectedSize = readUint32LE(dataView, trailerOffset + 4);

  const output = new Uint8Array(expectedSize);
  const result = inflateRaw(compressedData, output);
  const actualCrc = crc32(result);

  if (actualCrc !== expectedCrc) {
    throw new Error("Gzip CRC32 mismatch");
  }

  return result;
}

export function gzipCompressFallback(bytes: Uint8Array): Uint8Array {
  const chunks: Uint8Array[] = [];
  const header = new Uint8Array([
    Gzip.ID1,
    Gzip.ID2,
    Gzip.CM_DEFLATE,
    0, // flags
    0, 0, 0, 0, // mtime
    0, // xfl
    255, // OS unknown
  ]);
  chunks.push(header);

  let offset = 0;
  const length = bytes.length;

  if (length === 0) {
    const block = new Uint8Array(5);
    block[0] = 1; // BFINAL + stored block
    block[1] = 0;
    block[2] = 0;
    block[3] = 0xff;
    block[4] = 0xff;
    chunks.push(block);
  } else {
    while (offset < length) {
      const remaining = length - offset;
      const chunkSize = Math.min(0xffff, remaining);
      const block = new Uint8Array(5 + chunkSize);
      block[0] = offset + chunkSize >= length ? 1 : 0;
      block[1] = chunkSize & 0xff;
      block[2] = (chunkSize >>> 8) & 0xff;
      const inverted = (~chunkSize) & 0xffff;
      block[3] = inverted & 0xff;
      block[4] = (inverted >>> 8) & 0xff;
      block.set(bytes.subarray(offset, offset + chunkSize), 5);
      chunks.push(block);
      offset += chunkSize;
    }
  }

  const crc = crc32(bytes);
  const trailer = new Uint8Array(8);
  trailer[0] = crc & 0xff;
  trailer[1] = (crc >>> 8) & 0xff;
  trailer[2] = (crc >>> 16) & 0xff;
  trailer[3] = (crc >>> 24) & 0xff;

  const size = bytes.length >>> 0;
  trailer[4] = size & 0xff;
  trailer[5] = (size >>> 8) & 0xff;
  trailer[6] = (size >>> 16) & 0xff;
  trailer[7] = (size >>> 24) & 0xff;
  chunks.push(trailer);

  let totalLength = 0;
  for (const chunk of chunks) {
    totalLength += chunk.length;
  }

  const result = new Uint8Array(totalLength);
  let writeOffset = 0;
  for (const chunk of chunks) {
    result.set(chunk, writeOffset);
    writeOffset += chunk.length;
  }
  return result;
}
