import type { AuthorLanguageSpec, AuthorKeyword } from './language-core';

type KeywordInput = string | [string, number];

const C_STRINGS = [
  { quote: "'", escape: '\\' },
  { quote: '"', escape: '\\' },
];

const HASH_STRINGS = [
  { quote: "'", escape: '\\', allowMultiline: false },
  { quote: '"', escape: '\\', allowMultiline: false },
];

const JSON_STRINGS = [
  { quote: '"', escape: '\\', allowMultiline: false },
];

const PY_STRINGS = [
  { quote: "'", escape: '\\', allowMultiline: false },
  { quote: '"', escape: '\\', allowMultiline: false },
];

const YAML_STRINGS = [
  { quote: '"', escape: '\\', allowMultiline: true },
  { quote: "'", allowMultiline: true },
];

const TOML_STRINGS = [
  { quote: '"', escape: '\\', allowMultiline: true },
  { quote: "'", allowMultiline: true },
];

const DEFAULT_NUMBERS = {
  allowHex: true,
  allowBin: true,
  allowOct: true,
  allowUnderscore: true,
  allowExp: true,
  allowLeadingDot: true,
} as const;

const SIMPLE_NUMBERS = {
  allowHex: true,
  allowOct: true,
  allowUnderscore: true,
  allowExp: true,
  allowLeadingDot: true,
} as const;

const JSON_NUMBERS = {
  allowHex: false,
  allowBin: false,
  allowOct: false,
  allowUnderscore: false,
  allowExp: true,
  allowLeadingDot: false,
} as const;

const YAML_NUMBERS = {
  allowHex: false,
  allowBin: false,
  allowOct: true,
  allowUnderscore: true,
  allowExp: true,
  allowLeadingDot: false,
} as const;

const TOML_NUMBERS = {
  allowHex: true,
  allowBin: true,
  allowOct: true,
  allowUnderscore: true,
  allowExp: true,
  allowLeadingDot: false,
} as const;

function kw(words: readonly KeywordInput[]): AuthorKeyword[] {
  return words.map((item) =>
    typeof item === 'string' ? { word: item } : { word: item[0], code: item[1] }
  );
}

function cLike(
  name: string,
  keywords: readonly KeywordInput[],
  overrides: Partial<AuthorLanguageSpec> = {},
): AuthorLanguageSpec {
  const spec: AuthorLanguageSpec = {
    name,
    aliases: overrides.aliases ?? [name],
    keywords: kw(keywords),
    lineComments: overrides.lineComments ?? ['//'],
    blockComments: overrides.blockComments ?? [['/*', '*/']],
    strings: overrides.strings ?? C_STRINGS,
    numbers: overrides.numbers ?? DEFAULT_NUMBERS,
  };
  if (overrides.regex) spec.regex = overrides.regex;
  if (overrides.templates) spec.templates = overrides.templates;
  if (overrides.identStartRanges) spec.identStartRanges = overrides.identStartRanges;
  if (overrides.identPartRanges) spec.identPartRanges = overrides.identPartRanges;
  return spec;
}

function hashComment(
  name: string,
  keywords: readonly KeywordInput[],
  overrides: Partial<AuthorLanguageSpec> = {},
): AuthorLanguageSpec {
  const spec: AuthorLanguageSpec = {
    name,
    aliases: overrides.aliases ?? [name],
    keywords: kw(keywords),
    lineComments: overrides.lineComments ?? ['#'],
    strings: overrides.strings ?? HASH_STRINGS,
    numbers: overrides.numbers ?? SIMPLE_NUMBERS,
  };
  if (overrides.blockComments) spec.blockComments = overrides.blockComments;
  if (overrides.regex) spec.regex = overrides.regex;
  if (overrides.templates) spec.templates = overrides.templates;
  if (overrides.identStartRanges) spec.identStartRanges = overrides.identStartRanges;
  if (overrides.identPartRanges) spec.identPartRanges = overrides.identPartRanges;
  return spec;
}

// Minimal HTML/XML-like support: comments, strings, attributes and common tags
// Note: tag names and some common elements are added as keywords for better emphasis.
export const htmlLanguageSpec: AuthorLanguageSpec = {
  name: 'html',
  aliases: ['html', 'htm', 'xhtml', 'xml', 'svg'],
  keywords: kw([
    // common tags
    'html','head','body','script','style','link','meta','title','base','noscript',
    'header','footer','nav','main','section','article','aside','h1','h2','h3','h4','h5','h6',
    'div','span','a','p','ul','ol','li','dl','dt','dd','blockquote','pre','code','hr','br',
    'table','thead','tbody','tfoot','tr','th','td','caption','col','colgroup',
    'form','input','textarea','select','option','optgroup','label','button','fieldset','legend',
    'img','picture','source','figure','figcaption','video','audio','track','canvas','svg','path','circle','rect','g','defs','symbol','use',
    '!doctype'
  ]),
  // HTML comments <!-- --> as block comments
  blockComments: [['<!--', '-->']],
  // Attribute strings
  strings: [
    { quote: '"', escape: '\\', allowMultiline: false },
    { quote: '\'', escape: '\\', allowMultiline: false },
  ],
  // Numbers not especially used, keep simple defaults
  numbers: SIMPLE_NUMBERS,
};

export const builtinLanguageSpecs: readonly AuthorLanguageSpec[] = [
  {
    name: 'python',
    aliases: ['python', 'py', 'py3'],
    keywords: kw([
      'and',
      'as',
      'assert',
      'async',
      'await',
      'break',
      'class',
      'continue',
      'def',
      'del',
      'elif',
      'else',
      'except',
      'False',
      'finally',
      'for',
      'from',
      'global',
      'if',
      'import',
      'in',
      'is',
      'lambda',
      'None',
      'nonlocal',
      'not',
      'or',
      'pass',
      'raise',
      'return',
      'True',
      'try',
      'while',
      'with',
      'yield',
    ]),
    lineComments: ['#'],
    strings: PY_STRINGS,
    numbers: DEFAULT_NUMBERS,
  },
  cLike('java', [
    'abstract',
    'assert',
    'boolean',
    'break',
    'byte',
    'case',
    'catch',
    'char',
    'class',
    'const',
    'continue',
    'default',
    'do',
    'double',
    'else',
    'enum',
    'extends',
    'final',
    'finally',
    'float',
    'for',
    'goto',
    'if',
    'implements',
    'import',
    'instanceof',
    'int',
    'interface',
    'long',
    'native',
    'new',
    'package',
    'private',
    'protected',
    'public',
    'return',
    'short',
    'static',
    'strictfp',
    'super',
    'switch',
    'synchronized',
    'this',
    'throw',
    'throws',
    'transient',
    'try',
    'void',
    'volatile',
    'while',
  ]),
  cLike('c', [
    'auto',
    'break',
    'case',
    'char',
    'const',
    'continue',
    'default',
    'do',
    'double',
    'else',
    'enum',
    'extern',
    'float',
    'for',
    'goto',
    'if',
    'inline',
    'int',
    'long',
    'register',
    'return',
    'short',
    'signed',
    'sizeof',
    'static',
    'struct',
    'switch',
    'typedef',
    'union',
    'unsigned',
    'void',
    'volatile',
    'while',
  ], { aliases: ['c'] }),
  cLike('cpp', [
    'alignas',
    'alignof',
    'and',
    'and_eq',
    'asm',
    'auto',
    'bitand',
    'bitor',
    'bool',
    'break',
    'case',
    'catch',
    'char',
    'char16_t',
    'char32_t',
    'class',
    'compl',
    'const',
    'constexpr',
    'const_cast',
    'continue',
    'decltype',
    'default',
    'delete',
    'do',
    'double',
    'dynamic_cast',
    'else',
    'enum',
    'explicit',
    'export',
    'extern',
    'false',
    'float',
    'for',
    'friend',
    'goto',
    'if',
    'inline',
    'int',
    'long',
    'mutable',
    'namespace',
    'new',
    'noexcept',
    'not',
    'not_eq',
    'nullptr',
    'operator',
    'or',
    'or_eq',
    'private',
    'protected',
    'public',
    'register',
    'reinterpret_cast',
    'return',
    'short',
    'signed',
    'sizeof',
    'static',
    'static_assert',
    'static_cast',
    'struct',
    'switch',
    'template',
    'this',
    'thread_local',
    'throw',
    'true',
    'try',
    'typedef',
    'typeid',
    'typename',
    'union',
    'unsigned',
    'using',
    'virtual',
    'void',
    'volatile',
    'wchar_t',
    'while',
    'xor',
    'xor_eq',
  ], { aliases: ['cpp', 'c++', 'cc'] }),
  cLike('csharp', [
    'abstract',
    'as',
    'base',
    'bool',
    'break',
    'byte',
    'case',
    'catch',
    'char',
    'checked',
    'class',
    'const',
    'continue',
    'decimal',
    'default',
    'delegate',
    'do',
    'double',
    'else',
    'enum',
    'event',
    'explicit',
    'extern',
    'false',
    'finally',
    'fixed',
    'float',
    'for',
    'foreach',
    'goto',
    'if',
    'implicit',
    'in',
    'int',
    'interface',
    'internal',
    'is',
    'lock',
    'long',
    'namespace',
    'new',
    'null',
    'object',
    'operator',
    'out',
    'override',
    'params',
    'private',
    'protected',
    'public',
    'readonly',
    'ref',
    'return',
    'sbyte',
    'sealed',
    'short',
    'sizeof',
    'stackalloc',
    'static',
    'string',
    'struct',
    'switch',
    'this',
    'throw',
    'true',
    'try',
    'typeof',
    'uint',
    'ulong',
    'unchecked',
    'unsafe',
    'ushort',
    'using',
    'virtual',
    'void',
    'volatile',
    'while',
  ], { aliases: ['csharp', 'c#', 'cs'] }),
  cLike('go', [
    'break',
    'case',
    'chan',
    'const',
    'continue',
    'default',
    'defer',
    'else',
    'fallthrough',
    'for',
    'func',
    'go',
    'goto',
    'if',
    'import',
    'interface',
    'map',
    'package',
    'range',
    'return',
    'select',
    'struct',
    'switch',
    'type',
    'var',
  ], { aliases: ['go', 'golang'] }),
  cLike('rust', [
    'as',
    'async',
    'await',
    'break',
    'const',
    'continue',
    'crate',
    'dyn',
    'else',
    'enum',
    'extern',
    'false',
    'fn',
    'for',
    'if',
    'impl',
    'in',
    'let',
    'loop',
    'match',
    'mod',
    'move',
    'mut',
    'pub',
    'ref',
    'return',
    'self',
    'Self',
    'static',
    'struct',
    'super',
    'trait',
    'true',
    'type',
    'unsafe',
    'use',
    'where',
    'while',
  ]),
  cLike('swift', [
    'associatedtype',
    'break',
    'case',
    'catch',
    'class',
    'continue',
    'default',
    'defer',
    'deinit',
    'do',
    'else',
    'enum',
    'extension',
    'fallthrough',
    'false',
    'fileprivate',
    'for',
    'func',
    'guard',
    'if',
    'import',
    'in',
    'init',
    'inout',
    'internal',
    'let',
    'nil',
    'open',
    'operator',
    'private',
    'protocol',
    'public',
    'repeat',
    'return',
    'rethrows',
    'self',
    'static',
    'struct',
    'subscript',
    'super',
    'switch',
    'throw',
    'throws',
    'true',
    'try',
    'typealias',
    'var',
    'where',
    'while',
  ]),
  cLike('kotlin', [
    'as',
    'break',
    'class',
    'continue',
    'do',
    'else',
    'false',
    'for',
    'fun',
    'if',
    'in',
    'interface',
    'is',
    'null',
    'object',
    'package',
    'return',
    'super',
    'this',
    'throw',
    'true',
    'try',
    'typealias',
    'val',
    'var',
    'when',
    'while',
  ], { aliases: ['kotlin', 'kt', 'kts'] }),
  cLike('scala', [
    'abstract',
    'case',
    'catch',
    'class',
    'def',
    'do',
    'else',
    'extends',
    'false',
    'final',
    'finally',
    'for',
    'forSome',
    'if',
    'implicit',
    'import',
    'lazy',
    'match',
    'new',
    'null',
    'object',
    'override',
    'package',
    'private',
    'protected',
    'return',
    'sealed',
    'super',
    'this',
    'throw',
    'trait',
    'try',
    'true',
    'type',
    'val',
    'var',
    'while',
    'with',
    'yield',
  ]),
  cLike('dart', [
    'abstract',
    'as',
    'assert',
    'async',
    'await',
    'break',
    'case',
    'catch',
    'class',
    'const',
    'continue',
    'default',
    'deferred',
    'do',
    'dynamic',
    'else',
    'enum',
    'export',
    'external',
    'extends',
    'factory',
    'false',
    'final',
    'finally',
    'for',
    'get',
    'if',
    'implements',
    'import',
    'in',
    'interface',
    'is',
    'library',
    'mixin',
    'new',
    'null',
    'operator',
    'part',
    'rethrow',
    'return',
    'set',
    'static',
    'super',
    'switch',
    'sync',
    'this',
    'throw',
    'true',
    'try',
    'typedef',
    'var',
    'void',
    'while',
    'with',
    'yield',
  ]),
  hashComment('ruby', [
    'BEGIN',
    'END',
    'alias',
    'and',
    'begin',
    'break',
    'case',
    'class',
    'def',
    'defined?',
    'do',
    'else',
    'elsif',
    'end',
    'ensure',
    'false',
    'for',
    'if',
    'in',
    'module',
    'next',
    'nil',
    'not',
    'or',
    'redo',
    'rescue',
    'retry',
    'return',
    'self',
    'super',
    'then',
    'true',
    'undef',
    'unless',
    'until',
    'when',
    'while',
    'yield',
  ], { aliases: ['ruby', 'rb'], numbers: DEFAULT_NUMBERS }),
  cLike('php', [
    'abstract',
    'and',
    'array',
    'as',
    'break',
    'case',
    'catch',
    'class',
    'clone',
    'const',
    'continue',
    'declare',
    'default',
    'do',
    'echo',
    'else',
    'elseif',
    'empty',
    'endfor',
    'endforeach',
    'endif',
    'endswitch',
    'endwhile',
    'extends',
    'final',
    'finally',
    'for',
    'foreach',
    'function',
    'global',
    'goto',
    'if',
    'implements',
    'include',
    'include_once',
    'instanceof',
    'interface',
    'isset',
    'list',
    'namespace',
    'new',
    'or',
    'print',
    'private',
    'protected',
    'public',
    'require',
    'require_once',
    'return',
    'static',
    'switch',
    'throw',
    'trait',
    'try',
    'unset',
    'use',
    'var',
    'while',
    'xor',
  ], { lineComments: ['//', '#'], blockComments: [['/*', '*/']] }),
  {
    name: 'shell',
    aliases: ['shell', 'bash', 'sh', 'zsh', 'ksh'],
    keywords: kw([
      'case',
      'do',
      'done',
      'elif',
      'else',
      'esac',
      'fi',
      'for',
      'function',
      'if',
      'in',
      'select',
      'then',
      'until',
      'while',
    ]),
    lineComments: ['#'],
    strings: HASH_STRINGS,
    numbers: SIMPLE_NUMBERS,
  },
  {
    name: 'powershell',
    aliases: ['powershell', 'ps1', 'psm1'],
    keywords: kw([
      'begin',
      'break',
      'catch',
      'class',
      'continue',
      'data',
      'define',
      'do',
      'dynamicparam',
      'else',
      'elseif',
      'end',
      'enum',
      'exit',
      'filter',
      'finally',
      'for',
      'foreach',
      'from',
      'function',
      'if',
      'in',
      'param',
      'process',
      'return',
      'switch',
      'throw',
      'trap',
      'try',
      'until',
      'using',
      'while',
    ]),
    lineComments: ['#'],
    strings: HASH_STRINGS,
    numbers: DEFAULT_NUMBERS,
  },
  {
    name: 'json',
    aliases: ['json'],
    keywords: kw(['true', 'false', 'null']),
    strings: JSON_STRINGS,
    numbers: JSON_NUMBERS,
  },
  {
    name: 'yaml',
    aliases: ['yaml', 'yml'],
    keywords: kw(['true', 'false', 'null', 'yes', 'no', 'on', 'off']),
    lineComments: ['#'],
    strings: YAML_STRINGS,
    numbers: YAML_NUMBERS,
  },
  {
    name: 'toml',
    aliases: ['toml'],
    keywords: kw(['true', 'false', 'nan', 'inf']),
    lineComments: ['#'],
    strings: TOML_STRINGS,
    numbers: TOML_NUMBERS,
  },
  {
    name: 'ini',
    aliases: ['ini', 'cfg', 'conf'],
    keywords: kw(['true', 'false', 'on', 'off', 'yes', 'no']),
    lineComments: [';', '#'],
    strings: HASH_STRINGS,
    numbers: SIMPLE_NUMBERS,
  },
  {
    name: 'sql',
    aliases: ['sql'],
    keywords: kw([
      'select',
      'insert',
      'update',
      'delete',
      'from',
      'where',
      'join',
      'left',
      'right',
      'inner',
      'outer',
      'on',
      'group',
      'by',
      'order',
      'having',
      'limit',
      'offset',
      'into',
      'values',
      'create',
      'table',
      'primary',
      'key',
      'foreign',
      'constraint',
      'drop',
      'alter',
      'index',
      'view',
      'distinct',
      'case',
      'when',
      'then',
      'else',
      'end',
      'union',
      'all',
      'exists',
      'in',
      'like',
      'null',
      'is',
      'and',
      'or',
      'not',
    ]),
    lineComments: ['--'],
    blockComments: [['/*', '*/']],
    strings: [{ quote: "'", escape: "''" }, { quote: '"', escape: '""' }],
    numbers: DEFAULT_NUMBERS,
  },
  {
    name: 'lua',
    aliases: ['lua'],
    keywords: kw([
      'and',
      'break',
      'do',
      'else',
      'elseif',
      'end',
      'false',
      'for',
      'function',
      'goto',
      'if',
      'in',
      'local',
      'nil',
      'not',
      'or',
      'repeat',
      'return',
      'then',
      'true',
      'until',
      'while',
    ]),
    lineComments: ['--'],
    blockComments: [['--[[', ']]']],
    strings: HASH_STRINGS,
    numbers: DEFAULT_NUMBERS,
  },
  hashComment('perl', [
    'and',
    'cmp',
    'continue',
    'do',
    'else',
    'elsif',
    'eq',
    'for',
    'foreach',
    'ge',
    'gt',
    'if',
    'le',
    'lt',
    'ne',
    'not',
    'or',
    'package',
    'redo',
    'unless',
    'until',
    'while',
    'xor',
  ], { aliases: ['perl', 'pl', 'pm'], numbers: DEFAULT_NUMBERS }),
  {
    name: 'haskell',
    aliases: ['haskell', 'hs'],
    keywords: kw([
      'case',
      'class',
      'data',
      'default',
      'deriving',
      'do',
      'else',
      'if',
      'import',
      'in',
      'infix',
      'infixl',
      'infixr',
      'instance',
      'let',
      'module',
      'newtype',
      'of',
      'then',
      'type',
      'where',
    ]),
    lineComments: ['--'],
    blockComments: [['{-', '-}']],
    strings: HASH_STRINGS,
    numbers: DEFAULT_NUMBERS,
  },
  hashComment('elixir', [
    'alias',
    'and',
    'case',
    'cond',
    'def',
    'defmacro',
    'defmodule',
    'do',
    'else',
    'end',
    'false',
    'fn',
    'for',
    'if',
    'import',
    'in',
    'nil',
    'not',
    'or',
    'quote',
    'raise',
    'receive',
    'require',
    'super',
    'true',
    'try',
    'unless',
    'use',
    'with',
  ], { aliases: ['elixir', 'ex', 'exs'], numbers: DEFAULT_NUMBERS }),
  {
    name: 'erlang',
    aliases: ['erlang', 'erl'],
    keywords: kw([
      'after',
      'and',
      'andalso',
      'band',
      'begin',
      'bnot',
      'bor',
      'bsl',
      'bsr',
      'bxor',
      'case',
      'catch',
      'cond',
      'div',
      'end',
      'fun',
      'if',
      'not',
      'of',
      'orelse',
      'receive',
      'rem',
      'try',
      'when',
      'xor',
    ]),
    lineComments: ['%'],
    strings: HASH_STRINGS,
    numbers: DEFAULT_NUMBERS,
  },
  {
    name: 'clojure',
    aliases: ['clojure', 'clj', 'cljs', 'cljc'],
    keywords: kw([
      'def',
      'defn',
      'defmacro',
      'let',
      'loop',
      'if',
      'do',
      'recur',
      'case',
      'try',
      'catch',
      'throw',
      'finally',
      'fn',
      'macro',
      'quote',
      'var',
    ]),
    lineComments: [';'],
    strings: [{ quote: '"', escape: '\\', allowMultiline: false }],
    numbers: DEFAULT_NUMBERS,
  },
  hashComment('r', [
    'break',
    'else',
    'FALSE',
    'for',
    'function',
    'if',
    'in',
    'Inf',
    'NA',
    'NaN',
    'NULL',
    'repeat',
    'return',
    'TRUE',
    'while',
  ], { aliases: ['r', 'rscript'], numbers: DEFAULT_NUMBERS }),
  {
    name: 'dockerfile',
    aliases: ['dockerfile', 'docker'],
    keywords: kw([
      'FROM',
      'RUN',
      'CMD',
      'LABEL',
      'EXPOSE',
      'ENV',
      'ADD',
      'COPY',
      'ENTRYPOINT',
      'VOLUME',
      'USER',
      'WORKDIR',
      'ARG',
      'ONBUILD',
      'STOPSIGNAL',
      'HEALTHCHECK',
      'SHELL',
    ]),
    lineComments: ['#'],
    strings: HASH_STRINGS,
    numbers: SIMPLE_NUMBERS,
  },
  {
    name: 'make',
    aliases: ['make', 'makefile'],
    keywords: kw([
      'include',
      'define',
      'endef',
      'ifdef',
      'ifndef',
      'ifeq',
      'ifneq',
      'else',
      'endif',
    ]),
    lineComments: ['#'],
    numbers: SIMPLE_NUMBERS,
  },
  cLike('fsharp', [
    'abstract',
    'and',
    'as',
    'assert',
    'base',
    'begin',
    'class',
    'default',
    'delegate',
    'do',
    'done',
    'downcast',
    'downto',
    'elif',
    'else',
    'end',
    'exception',
    'extern',
    'false',
    'finally',
    'for',
    'fun',
    'function',
    'if',
    'in',
    'inherit',
    'inline',
    'interface',
    'internal',
    'lazy',
    'let',
    'match',
    'member',
    'module',
    'mutable',
    'namespace',
    'new',
    'not',
    'null',
    'of',
    'open',
    'or',
    'override',
    'private',
    'public',
    'rec',
    'return',
    'static',
    'struct',
    'then',
    'to',
    'true',
    'try',
    'type',
    'upcast',
    'use',
    'val',
    'void',
    'when',
    'while',
    'with',
    'yield',
  ], { aliases: ['fsharp', 'fs'] }),
  htmlLanguageSpec,
];

