import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const sourcePath = resolve(root, 'src/wasm/smdp-core.wat');
const wasmPath = resolve(root, 'src/wasm/smdp-core.wasm');
const modulePath = resolve(root, 'src/wasm/smdp-core-binary.ts');
const compiler = process.env.WAT2WASM || 'wat2wasm';

execFileSync(compiler, [sourcePath, '-o', wasmPath], { stdio: 'inherit' });

const base64 = readFileSync(wasmPath).toString('base64');
const wrapped = base64.match(/.{1,100}/g)?.map((line) => `  '${line}'`).join(' +\n') ?? "  ''";
const generated = `// Generated by scripts/build-wasm-core.ts. Do not edit manually.\n` +
  `export const SMDP_CORE_WASM_BASE64 =\n${wrapped};\n`;

writeFileSync(modulePath, generated);
