import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const compiler = process.env.WAT2WASM || 'wat2wasm';

const targets = [
  { file: 'smdp-core', constant: 'SMDP_CORE_WASM_BASE64' },
  { file: 'smdp-diagram-core', constant: 'SMDP_DIAGRAM_CORE_WASM_BASE64' },
] as const;

for (const target of targets) {
  const sourcePath = resolve(root, `src/wasm/${target.file}.wat`);
  const wasmPath = resolve(root, `src/wasm/${target.file}.wasm`);
  const modulePath = resolve(root, `src/wasm/${target.file}-binary.ts`);

  execFileSync(compiler, [sourcePath, '-o', wasmPath], { stdio: 'inherit' });

  const base64 = readFileSync(wasmPath).toString('base64');
  const wrapped = base64.match(/.{1,100}/g)?.map((line) => `  '${line}'`).join(' +\n') ?? "  ''";
  const generated = `// Generated by scripts/build-wasm-core.ts. Do not edit manually.\n` +
    `export const ${target.constant} =\n${wrapped};\n`;

  writeFileSync(modulePath, generated);
}
